export const seoKeywords: string[] = [
  // Personal / branding
  "mo",
  "mo barut",
  "mo code solutions",
  "Muhammet Barut",
  "Mo Barut developer",
  "barut",
  "mo dev",

  // General developer / freelance
  "developer",
  "developer for hire",
  "freelance developer",
  "freelance full-stack developer",
  "freelance programmer",
  "React developer",
  "React developer for hire",
  "Next.js development",
  "TypeScript developer",

  // Web development
  "web development services",
  "custom web applications",
  "SaaS development",
  "e-commerce development",
  "API development",
  "database design",
  "responsive web design",
  "web app development",
  "startup MVP development",
  "business web solutions",
  "full-stack web development services",
  "mobile responsive web apps",
  "performance-optimized websites",
  "scalable web applications",
  "modern UI/UX web design",

  // AI Integration & Automation
  "AI integration for business",
  "workflow automation services",
  "custom AI solutions",
  "AI-powered chatbots",
  "machine learning automation",
  "automate business processes with AI",
  "OpenAI API integration",
  "intelligent content automation",
  "AI SaaS development services",

  // Payment Processing
  "Stripe integration services",
  "secure online payment solutions",
  "subscription billing setup",
  "PCI-compliant payment processing",
  "e-commerce payment integration",
  "multi-currency payment setup",
  "recurring billing and invoicing",
  "online checkout system integration",
  "payment webhook integration",

  // SEO & GEO Optimization
  "technical SEO consultant",
  "SEO for small businesses",
  "GEO optimization services",
  "Core Web Vitals optimization",
  "schema markup expert",
  "AI-friendly SEO (GEO)",
  "on-page and off-page SEO services",
  "SEO audit and recommendations",
  "SEO performance optimization",
  "freelance SEO specialist",

  // Database Management
  "PostgreSQL database design",
  "Supabase real-time database setup",
  "scalable database architecture",
  "database migration services",
  "secure data storage solutions",
  "automated backup and recovery",
  "optimized queries for speed",
  "database management for SaaS",
  "API integration with databases",

  // Web Hosting & Maintenance
  "Vercel hosting setup",
  "cloud deployment services",
  "website maintenance and updates",
  "24/7 website monitoring",
  "SSL certificates and security updates",
  "continuous integration and deployment",
  "performance optimization for hosted apps",
  "freelance web hosting support",
  "domain management services",
  "priority technical support for websites",

  // Niche / hyper-specific keywords
  "React Next.js freelance developer",
  "full-stack TypeScript developer for hire",
  "startup MVP web developer",
  "custom SaaS web application",
  "mobile-first responsive web app",
  "scalable PostgreSQL database solutions",
  "Supabase real-time app developer",
  "Stripe subscription billing integration",
  "PCI-compliant payment developer",
  "technical SEO and GEO optimization expert",
  "AI automation developer for business",
  "OpenAI integration services for web apps",
  "AI workflow automation for startups",
  "performance-optimized React applications",
  "freelance developer for SaaS MVP",
  "web app optimization for Core Web Vitals",
  "schema markup implementation services",
  "AI-friendly content SEO consultant",
  "Next.js TypeScript web app specialist",
  "custom API development freelance"
];
