import { Brain, Code2, CreditCard, Database, Search, Server } from "lucide-react";

export const services = [
  {
    icon: Code2,
    title: "Web Development",
    description: "Custom web applications built with modern frameworks and best practices.",
    features: ["React & Next.js", "Responsive Design", "Performance Optimized", "SaaS MVP"],
    color: "from-blue-500 to-cyan-500",
    bgGlow: "group-hover:shadow-blue-500/50",
    detailedDescription:
      "Transform your vision into a powerful web application that drives business growth. I specialize in building lightning-fast, scalable applications using cutting-edge technologies like React, Next.js, and TypeScript.",
    benefits: [
      "Lightning-fast performance with 90+ PageSpeed scores",
      "Mobile-first responsive design that works on all devices",
      "SEO-optimized architecture for maximum visibility",
      "Scalable codebase that grows with your business",
      "Modern UI/UX that converts visitors into customers",
      "Clean, maintainable code following industry best practices",
    ],
    deliverables: [
      "Fully responsive web application",
      "Source code and documentation",
      "Deployment to production",
      "Post-launch support",
    ],
  },
  {
    icon: Brain,
    title: "AI Integration & Automation",
    description: "Leverage cutting-edge AI to automate workflows and enhance user experiences.",
    features: ["Any Integration", "Workflow Automation", "Smart Features", "AI SaaS"],
    color: "from-purple-500 to-pink-500",
    bgGlow: "group-hover:shadow-purple-500/50",
    detailedDescription:
      "Stay ahead of the competition by integrating AI into your applications. From intelligent chatbots to automated workflows, I help businesses leverage AI to save time, reduce costs, and deliver exceptional user experiences.",
    benefits: [
      "Reduce operational costs by automating repetitive tasks",
      "24/7 AI-powered customer support with chatbots",
      "Intelligent content generation and personalization",
      "Data analysis and insights powered by machine learning",
      "Seamless integration with OpenAI, Anthropic, and more",
      "Custom AI solutions tailored to your specific needs",
    ],
    deliverables: [
      "AI-powered features integrated into your app",
      "Custom prompts and fine-tuning",
      "API integration and optimization",
      "Training and documentation",
    ],
  },
  {
    icon: CreditCard,
    title: "Payment Processing",
    description: "Secure payment solutions with Stripe integration for seamless transactions.",
    features: ["Stripe Integration", "Subscription Billing", "Secure Checkout"],
    color: "from-emerald-500 to-teal-500",
    bgGlow: "group-hover:shadow-emerald-500/50",
    detailedDescription:
      "Start accepting payments in minutes with secure, PCI-compliant payment processing. I implement robust payment systems using Stripe that handle one-time purchases, subscriptions, and complex billing scenarios.",
    benefits: [
      "Accept credit cards, Apple Pay, Google Pay, and more",
      "Automated subscription billing and invoicing",
      "Secure, PCI-compliant payment processing",
      "Real-time payment tracking and analytics",
      "Support for multiple currencies and payment methods",
      "Webhook integration for automated workflows",
    ],
    deliverables: [
      "Complete payment system integration",
      "Checkout flow and payment forms",
      "Subscription management dashboard",
      "Payment webhook handlers",
    ],
  },
  {
    icon: Search,
    title: "SEO & GEO Optimization",
    description: "Boost your visibility with technical SEO, GEO and performance optimization.",
    features: ["Technical SEO", "GEO - SEO For AI", "Core Web Vitals", "Schema Markup"],
    color: "from-orange-500 to-red-500",
    bgGlow: "group-hover:shadow-orange-500/50",
    detailedDescription:
      "Get found by your target audience with comprehensive SEO & GEO optimization. I implement technical SEO best practices, optimize Core Web Vitals, and ensure your site ranks higher in search results. I also optimize for GEO (Generative Engine Optimization) which focuses on getting content recognized and used within AI-generated answers and summaries by tools like ChatGPT. This increases the changes for your brand/business to get mentioned in AI chat results",
    benefits: [
      "Higher search engine rankings and organic traffic",
      "Ensure your brand's content is chosen and featured in AI-generated answers and summaries",
      "Optimized Core Web Vitals for better user experience",
      "Structured data and schema markup implementation",
      "Meta tags, Open Graph, and Twitter Cards optimization",
      "XML sitemaps and robots.txt configuration",
      "Performance optimization for faster load times",
    ],
    deliverables: [
      "Complete SEO audit and recommendations",
      "Complete GEO audit and recommendations",
      "Technical SEO & GEO implementation",
      "Performance optimization",
      "Analytics and tracking setup",
    ],
  },
  {
    icon: Database,
    title: "Database Management",
    description: "Scalable database solutions with PostgreSQL, Supabase, and more.",
    features: ["PostgreSQL", "Real-time Data", "Data Migration"],
    color: "from-indigo-500 to-blue-500",
    bgGlow: "group-hover:shadow-indigo-500/50",
    detailedDescription:
      "Build a solid foundation for your application with robust database architecture. I design and implement scalable database solutions using PostgreSQL, Supabase, and modern ORMs that handle millions of records efficiently.",
    benefits: [
      "Scalable database architecture that grows with you",
      "Real-time data synchronization across devices",
      "Secure data storage with row-level security",
      "Automated backups and disaster recovery",
      "Optimized queries for lightning-fast performance",
      "Seamless data migration from existing systems",
    ],
    deliverables: [
      "Database schema design and implementation",
      "API endpoints for data access",
      "Data migration scripts",
      "Database documentation",
    ],
  },
  {
    icon: Server,
    title: "Web Hosting & Maintenance",
    description: "Reliable hosting and domain management with ongoing support and updates.",
    features: ["Cloud Deployment", "24/7 Monitoring", "Security Audits", "Regular Updates"],
    color: "from-slate-500 to-zinc-500",
    bgGlow: "group-hover:shadow-slate-500/50",
    detailedDescription:
      "Focus on your business while I handle the technical details. I provide reliable hosting on Vercel's global edge network with continuous monitoring, regular updates, and proactive maintenance to keep your site running smoothly.",
    benefits: [
      "99.9% uptime with global CDN distribution",
      "Automatic SSL certificates and security updates",
      "24/7 monitoring and instant issue resolution",
      "Regular performance optimization and updates",
      "Automated backups and version control",
      "Priority support for critical issues",
    ],
    deliverables: [
      "Production deployment on Vercel",
      "CI/CD pipeline setup",
      "Monitoring and alerting",
      "Monthly maintenance reports",
    ],
  },
];
