import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import ColorModeToggle from '@/components/ColorModeToggle';
import Nav from '@/components/Nav'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <ColorModeToggle />
        <Nav />
        {children}
        <div className='w-full h-[50px] bg-gray-800 text-gray-500 flex items-center px-10 text-sm'>
          &copy; 2023 copyright all right reserved
        </div>
      </body>
    </html>
  );
}
